# Generated by Django 3.2.6 on 2021-09-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_auto_20210929_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetpost',
            name='creator',
        ),
    ]
